clean-client:
	@rm -rf download
	@rm -rf upload

setup-client:
	@mkdir -p download
	@mkdir -p upload

clean-setup-client: clean-client setup-client

.PHONY: clean-client setup-client clean-setup-client
